#!/bin/bash

SCRIPT_FOLDER="$HOME/Scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
    nvim $SCRIPT_FILE
else
    echo '#!/bin/env bash' > $SCRIPT_FILE
    chmod +x $SCRIPT_FILE
    nvim $SCRIPT_FILE
fi
