#!/bin/env bash
# --- By Kiriyama ---

## Change as you want 

# Save to this Directory
RECDIR=~/Videos/Screenrecord

# Audio offset in seconds
DEOFFSET=1

# Frame Rate to record in (fps)
FR=30

# Resolution of the Video
resolution=1280x720

## No Touchy space from here 
## Daaaaaaaaaaate 
whenrec=$(date +"%d-%m-%y_%H-%M")

## da magical command, does magick!
## making a temp cache file 
mkdir -p ~/.cache/recscreen
TEMPDIR=~/.cache/recscreen

pw-record $TEMPDIR/audio.wav & \
ffmpeg \
    -f x11grab -framerate $FR -i :0.0 \
    -vcodec libx264 -crf 7 \
    -vf scale=$resolution:flags=lanczos \
    -preset ultrafast\
    $TEMPDIR/video.mkv 

ffmpeg \
    -i $TEMPDIR/video.mkv -i $TEMPDIR/audio.wav \
    -c:v copy -map 0:v:0 -map 1:a:0 -c:a aac -b:a 300k \
    $RECDIR/$whenrec.mkv


## Adding the delay and Cleaning up....
# ffmpeg \
    # -i $TEMPDIR/temp.mp4 \
    # -itsoffset $DEOFFSET \
    # -i $TEMPDIR/temp.mp4 \
    # # -vcodec copy -acodec copy \
    # -map 0:0 -map 1:1 \
    # $RECDIR/$whenrec.mp4

rm -rf $TEMPDIR
